#############################################################################
# Makefile for building: OpenMeshDecimater
# Generated by qmake (2.01a) (Qt 4.8.6) on: mer. oct. 8 14:23:20 2014
# Project:  OpenMeshDecimater.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile OpenMeshDecimater.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/include -I. -I/usr/local/include -I.
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS)  -L/usr/local/Cellar/qt/4.8.6/lib -L/usr/local/lib/OpenMesh/ -lOpenMeshCore -lOpenMeshTools 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		OpenMeshDecimater.pro
QMAKE_TARGET  = OpenMeshDecimater
DESTDIR       = 
TARGET        = OpenMeshDecimater

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenMeshDecimater.pro  /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile OpenMeshDecimater.pro
/usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile OpenMeshDecimater.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/OpenMeshDecimater1.0.0 || $(MKDIR) .tmp/OpenMeshDecimater1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OpenMeshDecimater1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/OpenMeshDecimater1.0.0/ && (cd `dirname .tmp/OpenMeshDecimater1.0.0` && $(TAR) OpenMeshDecimater1.0.0.tar OpenMeshDecimater1.0.0 && $(COMPRESS) OpenMeshDecimater1.0.0.tar) && $(MOVE) `dirname .tmp/OpenMeshDecimater1.0.0`/OpenMeshDecimater1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OpenMeshDecimater1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/local/include/OpenMesh/Core/IO/MeshIO.hh \
		/usr/local/include/OpenMesh/Core/System/config.h \
		/usr/local/include/OpenMesh/Core/System/compiler.hh \
		/usr/local/include/OpenMesh/Core/System/OpenMeshDLLMacros.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_store.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_types.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_rbo.hh \
		/usr/local/include/OpenMesh/Core/System/omstream.hh \
		/usr/local/include/OpenMesh/Core/System/mostream.hh \
		/usr/local/include/OpenMesh/Core/Utils/GenProg.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_binary.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_binary_spec.hh \
		/usr/local/include/OpenMesh/Tools/Utils/NumLimitsT.hh \
		/usr/local/include/OpenMesh/Tools/Utils/Config.hh \
		/usr/local/include/OpenMesh/Core/Geometry/VectorT.hh \
		/usr/local/include/OpenMesh/Core/Geometry/VectorT_inc.hh \
		/usr/local/include/OpenMesh/Core/Mesh/Status.hh \
		/usr/local/include/OpenMesh/Core/IO/SR_binary_vector_of_fundamentals.inl \
		/usr/local/include/OpenMesh/Core/IO/SR_binary_vector_of_string.inl \
		/usr/local/include/OpenMesh/Core/IO/SR_binary_vector_of_bool.inl \
		/usr/local/include/OpenMesh/Core/IO/StoreRestore.hh \
		/usr/local/include/OpenMesh/Core/IO/IOManager.hh \
		/usr/local/include/OpenMesh/Core/IO/Options.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/BaseReader.hh \
		/usr/local/include/OpenMesh/Core/IO/importer/BaseImporter.hh \
		/usr/local/include/OpenMesh/Core/Mesh/BaseKernel.hh \
		/usr/local/include/OpenMesh/Core/Utils/PropertyContainer.hh \
		/usr/local/include/OpenMesh/Core/Utils/Property.hh \
		/usr/local/include/OpenMesh/Core/Mesh/Handles.hh \
		/usr/local/include/OpenMesh/Core/Utils/BaseProperty.hh \
		/usr/local/include/OpenMesh/Core/Utils/SingletonT.hh \
		/usr/local/include/OpenMesh/Core/Utils/SingletonT.cc \
		/usr/local/include/OpenMesh/Core/IO/writer/BaseWriter.hh \
		/usr/local/include/OpenMesh/Core/IO/exporter/BaseExporter.hh \
		/usr/local/include/OpenMesh/Core/IO/importer/ImporterT.hh \
		/usr/local/include/OpenMesh/Core/Utils/vector_cast.hh \
		/usr/local/include/OpenMesh/Core/Utils/vector_traits.hh \
		/usr/local/include/OpenMesh/Core/Utils/color_cast.hh \
		/usr/local/include/OpenMesh/Core/Mesh/Attributes.hh \
		/usr/local/include/OpenMesh/Core/IO/exporter/ExporterT.hh \
		/usr/local/include/OpenMesh/Core/IO/IOInstances.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/OBJReader.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/OFFReader.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/PLYReader.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/STLReader.hh \
		/usr/local/include/OpenMesh/Core/IO/reader/OMReader.hh \
		/usr/local/include/OpenMesh/Core/IO/OMFormat.hh \
		/usr/local/include/OpenMesh/Core/Utils/Endian.hh \
		/usr/local/include/OpenMesh/Core/IO/OMFormatT.cc \
		/usr/local/include/OpenMesh/Core/IO/writer/OBJWriter.hh \
		/usr/local/include/OpenMesh/Core/IO/writer/OFFWriter.hh \
		/usr/local/include/OpenMesh/Core/IO/writer/STLWriter.hh \
		/usr/local/include/OpenMesh/Core/IO/writer/OMWriter.hh \
		/usr/local/include/OpenMesh/Core/IO/BinaryHelper.hh \
		/usr/local/include/OpenMesh/Core/IO/writer/PLYWriter.hh \
		/usr/local/include/OpenMesh/Core/Mesh/TriMesh_ArrayKernelT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/TriConnectivity.hh \
		/usr/local/include/OpenMesh/Core/Mesh/PolyConnectivity.hh \
		/usr/local/include/OpenMesh/Core/Mesh/ArrayKernel.hh \
		/usr/local/include/OpenMesh/Core/Mesh/ArrayItems.hh \
		/usr/local/include/OpenMesh/Core/Mesh/ArrayKernelT.cc \
		/usr/local/include/OpenMesh/Core/Mesh/IteratorsT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/CirculatorsT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/Traits.hh \
		/usr/local/include/OpenMesh/Core/Mesh/FinalMeshItemsT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/AttribKernelT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/TriMeshT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/PolyMeshT.hh \
		/usr/local/include/OpenMesh/Core/Geometry/MathDefs.hh \
		/usr/local/include/OpenMesh/Core/Mesh/PolyMeshT.cc \
		/usr/local/include/OpenMesh/Core/Geometry/LoopSchemeMaskT.hh \
		/usr/local/include/OpenMesh/Core/Mesh/TriMeshT.cc \
		/usr/local/include/OpenMesh/Tools/Decimater/DecimaterT.hh \
		/usr/local/include/OpenMesh/Tools/Utils/HeapT.hh \
		/usr/local/include/OpenMesh/Tools/Decimater/BaseDecimaterT.hh \
		/usr/local/include/OpenMesh/Tools/Decimater/ModBaseT.hh \
		/usr/local/include/OpenMesh/Core/Utils/Noncopyable.hh \
		/usr/local/include/OpenMesh/Tools/Decimater/CollapseInfoT.hh \
		/usr/local/include/OpenMesh/Tools/Decimater/BaseDecimaterT.cc \
		/usr/local/include/OpenMesh/Tools/Decimater/DecimaterT.cc \
		/usr/local/include/OpenMesh/Tools/Decimater/ModQuadricT.hh \
		/usr/local/include/OpenMesh/Core/Geometry/QuadricT.hh \
		/usr/local/include/OpenMesh/Tools/Decimater/ModQuadricT.cc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

